version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3307:3307
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=tpachato
     - MYSQL_USER=root
     - MYSQL_PASSWORD=

  spring_app:
    image: reirav/springdevopsapp
    container_name: springdevopsapp
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&serverTimezone=UTC
    ports:
     - 8080:8080
    depends_on:
     - mysqldb
